### ISSUE TITLE
[Font Bakery Dashboard] fail to create family: Bebas Neue

### ISSUE THREAD

**Issue by vv-monsalve** [dharmatype/Bebas-Neue#3]
GitHub PR Server can't dispatch Pull Request. ERROR Error: Signature author is required. / Don't understand what it means.
Also,"designated GitHub branch page" (link) was broken

[full report](https://fontbakery.graphicore.de/dispatcher/process/8638f358-dc83-4cc1-a824-576aaea4a190)

# Step # 2 Create the Pull Request

**finished: FAILED**

Failing with reason: 

### Task SignOffAndDispatch FAILED

**GitHub PR Server** can't dispatch Pull Request.

 **ERROR** Error: Signature author is required.

[designated GitHub branch page](https://github.com/graphicore/googleFonts/tree/Font_Bakery_Dispatcher_2019_09_12_ofl_bebasneue)

**Comment by dharmatype** [comment]
Do you know how to fix this problem?

**Comment by dharmatype** [comment]
What is "Signature author" ?

**Comment by dharmatype** [comment]
Please try again.

**Comment by vv-monsalve** [comment]
We are making some test on the process, we'll check this and let you know in case we need for you to do something.

**Comment by graphicore** [comment]
please ignore this :-)

**Comment by graphicore** [comment]
I hope this explains it: https://github.com/googlefonts/fontbakery-dashboard/issues/124#issuecomment-534579210

This issue can be closed IMO.
